I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cherryRoute.rpy", line 35, in script
    me "[Huh.]"
KeyError: u'Huh'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/cherryRoute.rpy", line 35, in script
    me "[Huh.]"
  File "C:\Users\Leo\Downloads\renpy-7.4.8-sdk/renpy/ast.py", line 716, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Leo\Downloads\renpy-7.4.8-sdk/renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "C:\Users\Leo\Downloads\renpy-7.4.8-sdk/renpy/character.py", line 1210, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\Leo\Downloads\renpy-7.4.8-sdk/renpy/character.py", line 1129, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\Leo\Downloads\renpy-7.4.8-sdk/renpy/character.py", line 1109, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Leo\Downloads\renpy-7.4.8-sdk/renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'Huh'

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
GameJam 1.0
Sat Aug 14 17:55:53 2021
